### ISSUE TITLE
use SSHTunnelForwarder transfer file fail

### ISSUE THREAD

**Issue by fanwz** [pahaz/sshtunnel#115]
when use the SSHTunnelForwarder to connect the server and add port forward
target server A
relay server B
A B in the same lan
my pc on another lan
I use SSHTunnelForwarder connect B and forward port to A's SSH port
the same as ssh -L port1:B_IP:22 A_IP
the ssh login is OK,and can use the command line.
but when use the scp or rsync transfer file,there is some problem
if the file big than 4K, the connection(with A ssh) will lost
I check the server A's log,it show 

> Corrupted MAC on input.
sshd[21300]: ssh_dispatch_run_fatal: Connection from **serverB_IP** port 63742: message authentication code incorrect
sshd[21300]: pam_unix(sshd:session): session closed for user root

when transfer file for B to A with scp  directly,there is no problem.
I also try another method.
I use the putty's tunnel to acheive the same func, it's OK too.
so I think it's sshtunnel problem.

**Comment by fernandezcuesta** [comment]
Have a look first at [serverfault threads](https://serverfault.com/questions/338439/ssh-sessions-terminate-abruptly-with-message-corrupted-mac-on-input-disconnect)

**Comment by fanwz** [comment]
@fernandezcuesta I have tried this. but the problem is the same. I use the putty is OK.

**Comment by fanwz** [comment]
@fernandezcuesta only ome server has this prolbem.I don't know what config inpect this.But putty is OK

**Comment by nalvarez1** [comment]
I just spent the past several days troubleshooting this same problem.  There is a bug in sshtunnel.py in the `_ForwardHandler._redirect()` method.  When data is received on the locally bound socket it calls `chan.send(data)` to send the data across the channel; however, the return value of this call is ignored. 

The python documentation for socket.send() says, "Applications are responsible for checking that all data has been sent; if only some of the data was transmitted, the application needs to attempt delivery of the remaining data."  In the case where a lot of data is being written to the tunnel really fast, the send buffer/window may fill up, and instead of sending all the data it will only send a portion of it.  The return value indicates how much of the data was actually sent.  (With the current code, throttling back the file transfer (e.g. sftp with -l option) seems to avoid the problem).

Similarly on the receiving end, the return value of the call to `self.request.send(data)` needs to be checked as well.  As a quick hack, I tried changing the `send()` calls to `sendall()`, which blocks until everything is sent, and the problem disappeared.  Blocking in this way may not be the best fix though.

**Comment by fernandezcuesta** [comment]
Hi, thanks for the thorough analysis. Please feel free to send a PR if you find the way to fix it :+1:

**Comment by pranky89** [comment]
This is causing problem in my testing as well, is there any way you can fix it? i have noticed the same thing, on a machine where it's failing, i see that the socket is getting closed which is in "ESTABLISHED" state and on the other hand, a slow network machine is working just fine with it.

**Comment by pranky89** [comment]
If there are others who are waiting for it to fixed, just forget about this library and start using the plink.exe that comes with putty to automate the sshtunnel. it's far easier and controllable than this lib for which you have to wait for the bugs to be fixed.

**Comment by fernandezcuesta** [comment]
Hi there. Suggested solutions where already implemented such as using
.sendall() instead if .send().
Without reproducible use case ir a detailed error analysis is not possible
to fix anything.
Using other tools such as plink or OpenSSH is something well known by
minimally experienced users. Simply complaining about bugs not being fixed
with 'does not work on my machine' arguments doesnt give any hint to
maintainers.

**Comment by pahaz** [comment]
I think it should be fixed. If you still have any problem feel free to reopen the issue or open a new one.
