### ISSUE TITLE
Use credentials for endhost

### ISSUE THREAD

**Issue by Phxntxm** [pahaz/sshtunnel#143]
I feel as if I'm missing something here, because this should be fairly basic but I cannot figure it out....I have a situation where I want to essentially use example 2 exactly....however the username/password for the remote_bind_address' host is different than the username/password for the proxy host.

I see no way to specify these credentials, the only credentials I see is ssh_username/ssh_password which from my understanding, will be used for both? If I'm missing something here, which I feel like I am, can someone explain what it is I'm missing.

**Comment by Phxntxm** [comment]
I just realized what I was missing, the tunneling does not *open* the connection, the tunnel makes the connection *available* which just means when doing the `client.connect` part in the example, you provide the credentials there.

**Comment by bsamuel-ui** [comment]
Yup. Since I started writing this...

If you're forwarding port 22 via your proxy, the tunnel doesn't (can't) know what you're sending over it. It's just setting up a dumb pipe for you. So you're going to auth to remote in a completely separate operation.

Example 2 is like running `ssh -L bindport:remotehost proxyuser@proxyhost`, so you still need to run `ssh remoteuser@localhost -p bindport`.
