### ISSUE TITLE
sshtunnel.stop() blocking if sshclient not close, any way to kill?

### ISSUE THREAD

**Issue by V0idk** [pahaz/sshtunnel#169]

**Comment by mdavis-xyz** [comment]
Your question has no detail. Please provide a minimal working example. If you don't put much effort into asking the question, you can't expect much effort from others to answer the question.

I *think* I have the same issue in #201 , but I'm not sure because you have no detail about what your code is like, which version you're using etc. Have a look at #201 and see if those settings help.

**Comment by pahaz** [comment]
Sinc **0.2.2**.
If you don't want to wait for all active connections to close use `tunnel.stop(force=True)`.
If you need to wait for all active connections to close use `tunnel.stop()`.

Also, I have a plane to use `tunnel.stop(force=True)` in context exit, after some discussion it may be the default behavior. Details here: https://github.com/pahaz/sshtunnel/pull/209

I think it's duplicate issues.

**Comment by mdavis-xyz** [comment]
Ok, thanks.

And just to clarify, do I need the following while loops, if not using `force=True`?

```
server.start()

while not server.is_active:
    sleep(1)
    
# do work

server.stop()
while server.is_active:
    sleep(1)
```

**Comment by pahaz** [comment]
What do you really want to achieve? Currently, `server.stop` is blocking until the end of all connections. `force` just close the ssh tunnel and forces active connection to close.

I don't know the case where you need this:
```
while server.is_active:
    sleep(1)
```

Because after the `server.stop()` call your will get `server.is_active == False`.

**Comment by mdavis-xyz** [comment]
Ah ok. Thanks.

I think I was just getting confused and added this back when I was debugging why it was hanging.
